bindd = $mainMod, SPACE, Launch walker, exec, $scripts/launch-walker
bindd = $mainMod $shift, S, Show key bindings, exec, $scripts/keybindings-menu
bindrd = $mainMod, U, Generate UUID, exec, $scripts/uuid-menu