bindd = $mainMod, comma, Dismiss last notification, exec, swaync-client --hide-latest
bindd = $mainMod $shift, comma, Dismiss all notifications, exec, swaync-client --hide-all
bindd = $mainMod $ctrl, comma, Toggle silencing notifications, exec, $scripts/toggle-dnd
bindd = $mainMod $alt, comma, Invoke last notification, exec, swaync-client --toggle-panel