- name: Install base fonts
  pacman:
    name:
      - ttf-font-awesome
      - ttf-cascadia-mono-nerd
      - noto-fonts
      - noto-fonts-emoji
      - ttf-jetbrains-mono-nerd
      - noto-fonts-cjk
      - noto-fonts-extra
      - woff2-font-awesome
    state: present
  tags: display, fonts