---
# Display & Desktop Foundation setup
- name: Import display manager installation tasks
  include_tasks: display_manager.yml
  tags: display, sddm

- name: Import fonts installation tasks
  include_tasks: fonts.yml
  tags: display, fonts

- name: Import themes installation tasks
  include_tasks: themes.yml
  tags: display, themes