# Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule {
    name = jetbrains-splash
    match:class = ^(jetbrains-.*)$
    match:title = ^(splash)$
    match:float = true
    tag = +jetbrains-splash
    center = on
    no_focus = on
    border_size = 0
}

# Center popups/find windows
windowrule {
    name = jetbrains-popups
    match:class = ^(jetbrains-.*)$
    match:title = ^()$
    match:float = true
    tag = +jetbrains
    center = on
    stay_focused = on
    border_size = 0
}

# Disable window flicker when autocomplete or tooltips appear
windowrule {
    name = jetbrains-autocomplete
    match:class = ^(jetbrains-.*)$
    match:title = (^win.*)$
    match:float = true
    no_initial_focus = on
}

# Disable mouse focus
windowrule {
    name = jetbrains-mouse-focus
    match:class = ^(jetbrains-.*)$
    no_follow_mouse = on
}
