---
# Display role variables

sddm_theme: "sddm-sugar-candy"
cursor_theme: "bibata-cursor-theme"
gtk_theme: "Catppuccin-Mocha-Standard-Rosewater-Dark"
gtk_icon_theme: "Papirus"
gtk_cursor_theme: "Bibata-Modern-Classic"
gtk_font: "Cascadia Code Nerd Font 11"

font_packages:
  - ttf-font-awesome
  - ttf-cascadia-mono-nerd
  - noto-fonts
  - noto-fonts-emoji
  - ttf-jetbrains-mono-nerd
  - noto-fonts-cjk
  - noto-fonts-extra
  - woff2-font-awesome

theme_packages:
  - name: catppuccin-gtk-theme-mocha
    category: theme
    reason: "Catppuccin mocha theme for file manager"
    aur: true
  - name: bibata-cursor-theme
    category: theme
    reason: "Theme for cursor"
    aur: true
  - name: papirus-icon-theme
    category: theme
    reason: "Icon theme"
    aur: false

user_config_dirs:
  - .config
  - .local/share/icons
  - .local/share/themes